# Generated by Django 4.2.4 on 2023-09-09 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Edition')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Platform')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Game Name')),
                ('backgroundImage', models.ImageField(blank=True, null=True, upload_to='media/background_images/', verbose_name='Background Image')),
                ('iframe', models.CharField(blank=True, max_length=100, null=True, verbose_name='')),
                ('leftPng', models.ImageField(blank=True, null=True, upload_to='media/background_images/', verbose_name='Left Png')),
                ('rightPng', models.ImageField(blank=True, null=True, upload_to='media/background_images/', verbose_name='Right Png')),
                ('pngShadowColor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Png Shadow Color')),
                ('aboutImage', models.ImageField(blank=True, null=True, upload_to='media/background_images/', verbose_name='About Image')),
                ('about', models.CharField(blank=True, max_length=200, null=True, verbose_name='About')),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Price')),
                ('edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.edition', verbose_name='Edition')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.platform', verbose_name='Platform')),
            ],
        ),
    ]
