# Generated by Django 4.2.4 on 2023-09-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_rename_games_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='editionImage',
            field=models.ImageField(blank=True, null=True, upload_to='media/background_images/', verbose_name='Edition Image'),
        ),
        migrations.AlterField(
            model_name='game',
            name='iframe',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Iframe'),
        ),
    ]
