# Generated by Django 4.2.4 on 2023-09-14 08:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appMy', '0008_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='basket',
            field=models.ManyToManyField(related_name='basket_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='basket_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
